name: Playwright E2E Tests

on:
  pull_request:
    branches:
      - 4.x-develop

jobs:
  playwright:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://localhost:8888

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Install and build GovCMS
        run: |
          docker compose up -d --build

      - name: Clone test repo
        run: |
          git clone https://github.com/jackwrfuller/govcms-testing.git playwright-tests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright dependencies
        working-directory: playwright-tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: playwright-tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/playwright-report


